export const QUERY_UPDATED = "Search/QUERY_UPDATED";
export const RESULTS_REQUESTED = "Search/RESULTS_REQUESTED";
export const RESULTS_RESOLVED = "Search/RESULTS_RESOLVED";
export const RESULTS_REJECTED = "Search/RESULTS_REJECTED";
