export const GAMES_RESOLVED = "Collection/GAMES_RESOLVED";
export const GAME_UPDATE_RESOLVED = "Collection/GAME_UPDATE_RESOLVED";
export const GAME_BULK_UPDATE_RESOLVED = "Collection/GAME_BULK_UPDATE_RESOLVED";
